### ISSUE TITLE
` --useEnumType` break on integer enum

### ISSUE THREAD

**Issue by trim21** [oazapfts/oazapfts#348]
I'm trying to generate client with `--useEnumType` but it throw a runtime TypeError in ts package

I guess this is because I'm using int enum value?

```text
>  oazapfts api.yaml --useEnumType

C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:18305
        return s.replace(escapedCharsRegExp, getReplacement);
                 ^

TypeError: s.replace is not a function
    at escapeString (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:18305:18)
    at escapeNonAsciiString (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:18310:13)
    at Object.getLiteralText (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:15089:34)
    at getLiteralTextOfNode (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:116991:23)
    at emitLiteral (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:114285:24)
    at pipelineEmitWithHintWorker (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:114082:32)
    at pipelineEmitWithHint (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:113708:17)
    at pipelineEmitWithComments (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:117396:13)
    at pipelineEmit (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:113648:13)
    at emitExpression (C:\Users\Trim21\proj\bangumi\frontend\node_modules\.pnpm\typescript@4.9.3\node_modules\typescript\lib\typescript.js:113632:13)

Node.js v18.12.1
C:\Users\Trim21\proj\bangumi\frontend\packages\client:
```
[spec.zip](https://github.com/oazapfts/oazapfts/files/10175154/api.zip)

**Comment by fgnass** [comment]
Fixed in oazapfts@4.5.1
