### ISSUE TITLE
I was able to generate this code in oazapfts 3.6.0, but after upgrading to 4.10.0, I get RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by kahirokunn** [oazapfts/oazapfts#504]
[swagger.json](https://github.com/oazapfts/oazapfts/files/13163008/swagger.json)

error log

```log
RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at ApiGenerator.checkSchemaOnlyMode (xxxxxx/node_modules/oazapfts/src/codegen/generate.ts:807:18)
    at xxxxxx/node_modules/oazapfts/src/codegen/generate.ts:815:14
    at Array.some (<anonymous>)
    at ApiGenerator.checkSchemaOnlyMode (xxxxxx/node_modules/oazapfts/src/codegen/generate.ts:814:8)
    at ApiGenerator.checkSchemaOnlyMode (xxxxxx/node_modules/oazapfts/src/codegen/generate.ts:788:16)
    at xxxxxx/node_modules/oazapfts/src/codegen/generate.ts:815:14
    at Array.some (<anonymous>)
    at ApiGenerator.checkSchemaOnlyMode (xxxxxx/node_modules/oazapfts/src/codegen/generate.ts:814:8)
    at ApiGenerator.checkSchemaOnlyMode (xxxxxx/node_modules/oazapfts/src/codegen/generate.ts:801:16)
error: Uncaught (in promise) ProcessOutput {}
error: Recipe `generate-code` failed with exit code 1
```

The cause is not known. 😭

**Comment by bdm-k** [comment]
This issue has already been reported in #486.

**Comment by kahirokunn** [comment]
Oh, Thx 🙏
