### ISSUE TITLE
[Bug] Broken enum types when hyphens in names

### ISSUE THREAD

**Issue by Fi1osof** [oazapfts/oazapfts#542]
Part of schema:
```yml
    TriggerPlaylistSpec:
      type: object
      properties:
        playlist:
          type: string
          format: uri
          maxLength: 200
        media-protocol:
          enum:
          - hls
          - mss
          - dash
```

Error:
```
getTrueEnum propName media-protocol
getTrueEnum proposedName media-protocol
SyntaxError: ';' expected. (513:28)
  511 | export type TriggerPlaylistSpec = {
  512 |     playlist: string;
> 513 |     "media-protocol": media-protocol;
      |                            ^
  514 | };
  515 | export type TriggerCcidSpec = {
  516 |     ccids: string[];
    at D (/app/node_modules/prettier/parser-typescript.js:1:17100)
    at LT (/app/node_modules/prettier/parser-typescript.js:257:10765)
    at Object.RT [as parse] (/app/node_modules/prettier/parser-typescript.js:257:11074)
    at Object.parse (/app/node_modules/prettier/index.js:7515:23)
    at coreFormat (/app/node_modules/prettier/index.js:8829:18)
    at formatWithCursor2 (/app/node_modules/prettier/index.js:9021:18)
    at /app/node_modules/prettier/index.js:38168:12
    at Object.format (/app/node_modules/prettier/index.js:38182:12)
    at prettify (/app/packages/redux-toolkit/packages/rtk-query-codegen-openapi/src/utils/prettier.ts:35:19)
    at generateEndpoints (/app/packages/redux-toolkit/packages/rtk-query-codegen-openapi/src/index.ts:20:63) {
  loc: { start: { line: 513, column: 28 } },
  codeFrame: '\x1B[0m \x1B[90m 511 |\x1B[39m \x1B[36mexport\x1B[39m type \x1B[33mTriggerPlaylistSpec\x1B[39m \x1B[33m=\x1B[39m {\x1B[0m\n' +
    '\x1B[0m \x1B[90m 512 |\x1B[39m     playlist\x1B[33m:\x1B[39m string\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 513 |\x1B[39m     \x1B[32m"media-protocol"\x1B[39m\x1B[33m:\x1B[39m media\x1B[33m-\x1B[39mprotocol\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m     |\x1B[39m                            \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 514 |\x1B[39m }\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 515 |\x1B[39m \x1B[36mexport\x1B[39m type \x1B[33mTriggerCcidSpec\x1B[39m \x1B[33m=\x1B[39m {\x1B[0m\n' +
    '\x1B[0m \x1B[90m 516 |\x1B[39m     ccids\x1B[33m:\x1B[39m string[]\x1B[33m;\x1B[39m\x1B[0m'
}
```

My very dirty [fix](https://github.com/Fi1osof/oazapfts/commit/0020d5c1c738088fd266928a651b7bf59d1e91bb): 
```ts
    propName = (propName + "-enum")
      .split("-")
      .map((n) => _.upperFirst(n))
      .join("")

    const proposedName = schema.title || propName;
```

**Comment by Xiphe** [comment]
Good catch! Agree that we should camel-case these!
