### ISSUE TITLE
Package cannot be resolved in vite application

### ISSUE THREAD

**Issue by jheinzel** [oazapfts/oazapfts#559]
I recently upgraded my web application to the most recent release of oazapfts (version 5.1.3). Following this update, I have been unable to access certain library functions, such as ok. This issue occurs in both a TypeScript-based React application and a standard TypeScript application, each built on the vite framework. When trying to use `ok` the following error message is produced:

```text
  VITE v5.0.12  ready in 463 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
21:08:37 [vite] Internal server error: Failed to resolve entry for package "oazapfts". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "oazapfts" package
  Plugin: vite:import-analysis
  File: C:/Temp/swt6x/ozapfts/test-ozapfts/src/main.ts
      at packageEntryFailure (file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29443:17)
      at resolvePackageEntry (file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29438:9)
      at tryNodeResolve (file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:29210:20)
      at Context.resolveId (file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:28978:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:63987:32)
      at async TransformContext.resolve (file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:63692:23)
      at async normalizeUrl (file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62029:34)
      at async file:///C:/Temp/swt6x/ozapfts/test-ozapfts/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62191:47
      at async Promise.all (index 0)
21:08:37 [vite] Pre-transform error: Failed to resolve entry for package "oazapfts". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "oazapfts" package
```

This issue started presenting itself from version 5.1.1 onward. Previously, with version 5.1.0, the application functioned as expected without any issues.

Steps to reproduce this behavior:
* `npm create vite@latest test-ozapfts -- --template vanilla-ts`
* cd ./test-ozapfts
* `npm install oazapfts`
*  generate a proxy for an arbitrary API (I used petstore)
*  Replace the code in `main.ts` with the following code fragment:
   ```ts
   import { ok } from 'oazapfts'
   import { findPetsByStatus } from './petstore-service';
   const pets = await ok(findPetsByStatus(["pending"]))
   ```
 * `npm run dev`

**Comment by jheinzel** [comment]
I suppose that an export for the main entry point is missing:
```json
"exports": {
  ".": {
    "require": "./lib/index.js",
    "import": "./lib/index.js"
  },
  ...
```

**Comment by Xiphe** [comment]
Hi @jheinzel thanks for bringing this up! Gonna look at this now

**Comment by Xiphe** [comment]
I suppose you're right. I have added the `.` export can you check `v5.1.4`?

**Comment by jheinzel** [comment]
Now it works. Thanks for the quick fix.
