### ISSUE TITLE
TypeError: c.identifierToKeywordKind is not a function

### ISSUE THREAD

**Issue by gugahoi** [oazapfts/oazapfts#673]
I'm having trouble generating a client for a given OpenAPI spec.

The spec I am using is hosted here: https://dash.readme.com/api/v1/api-registry/4rlk1xm0uio155

I am using `"oazapfts": "^6.1.0"`. Any ideas what I might be doing wrong?

```
❯ npx oazapfts ~/Downloads/4rlk1xm0uio155.json  src/clients/basiq/core.ts
file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:1322
  return !!e && e.kind === c.SyntaxKind.Identifier && c.identifierToKeywordKind(e) === void 0;
                                                        ^

TypeError: c.identifierToKeywordKind is not a function
    at H (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:1322:57)
    at Te (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:1192:33)
    at M (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:1099:114)
    at file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:1093:19
    at Array.map (<anonymous>)
    at ee (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:1092:7)
    at $e (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:58:10)
    at st.generateApi (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/tscodegen-wH2Xseqv.js:748:20)
    at l (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/index.js:7:25)
    at j (file:///Users/guga/Projects/joinflux/flux/packages/api-service/node_modules/oazapfts/index.js:14:13)

Node.js v20.17.0
```

**Comment by Xiphe** [comment]
Sorry for the late reply I've just tried to reproduce this with the latest version on couldn't create the bug.

So either it's magically fixed on our end or the spec has been updated to not run into this anymore?

Please reopen in case the issue persists.
