### ISSUE TITLE
"Can't find paths" when multiple input schema files

### ISSUE THREAD

**Issue by sebqq** [oazapfts/oazapfts#675]
Hello, I'm using this tool indirectly (via rtk-query codegen) and I have found the following bug?

My use case is having multiple input YAML schemas. I have one 'common' schema (shared types are stored here) and another - module-specific openapi schema files.

Currently, I'm not able to generate my TS client and I have prepared a very simplified reproducible example below:

**test.yaml**
```yaml
openapi: 3.0.0
info:
  description: API in Springboot.
  version: 0.0.1
  title: Extended Web API

paths:
  /searches/{id}:
    get:
      operationId: getSearches
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
components:
  schemas:
    SearchResponse:
      type: object
      required:
        - subscriber
        - result
      properties:
        subscriber:
          $ref: './common-test.yaml#/components/schemas/Subscriber'
        result:
          nullable: true
          allOf:
            - $ref: './common-test.yaml#/components/schemas/PatientSearchResult'
```

**common-test.yaml**:
```yaml
openapi: 3.0.0
info:
  description: API in Springboot.
  version: 0.0.1
  title: Common Web API

components:
  schemas:
    Address:
      type: object
      required:
        - city
        - state
        - zip
        - address
      properties:
        city:
          type: string
        state:
          type: string
        zip:
          type: string
        address:
          type: string
    PatientSearchResult:
      type: object
      required:
        - id
        - active
      properties:
        id:
          type: integer
        createdTime:
          type: string
        deactivateDate:
          type: string
        deactivateBy:
          type: string
        active:
          type: boolean
        lastChange:
          type: string
        subscriber:
          $ref: '#/components/schemas/InsuranceSubscriber'
    InsuranceSubscriber:
      type: object
      required:
        - subscriberId
        - firstName
        - lastName
      properties:
        subscriberId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    Sex:
      type: string
      enum:
        - M
        - F
        - U
    Subscriber:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dob:
          type: string
        address:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/Address'
```

When I run the generation command like `yarn oazapfts input/test.yaml output/ts-client.ts` the following error is thrown:

```bash
Error: Can't find paths,/searches/{id},get,responses,200,content,application/json,schema,properties,subscriber,properties,address,allOf,0
    at st.resolve (file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:244:13)
    at st.getRefAlias (file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:284:20)
    at st.getBaseTypeFromSchema (file:///Users/PATH/uni-gui/node_modules/oazapfts/tscodegen-wH2Xseqv.js:407:19)
    at st.getTypeFromSchema (file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:396:20)
    at file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:612:20
    at Array.map (<anonymous>)
    at st.getTypeFromProperties (file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:610:8)
    at st.getBaseTypeFromSchema (file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:481:55)
    at st.getTypeFromSchema (file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:396:20)
    at file:///Users/PATH/node_modules/oazapfts/tscodegen-wH2Xseqv.js:612:20
```

Now, when I merge `common-test.yaml` schema into `test.yaml` before generation, the error is no longer present. Sadly, I'm not the author of the API schema, so I have to work with separate schemas with references.

Any help would be much appreciated.
Thanks!

**Comment by Xiphe** [comment]
I @sebqq, sorry for the inconveniences.
This should™ be handled by  [`SwaggerParser.bundle(spec);`](https://github.com/oazapfts/oazapfts/blob/main/packages/codegen/src/index.ts#L46-L48) 

I currently don't have the capacity to look into this myself.

**Comment by hyakt** [comment]
Hi there.
I’m using this via msw-auto-mock, and we’ve run into the same issue in our project. I’m not very familiar with OpenAPI, so apologies if I’m off-base, but how about adding an option to use `SwaggerParser.dereference(spec)` instead of `SwaggerParser.bundle(spec)`?

When I searched around, I found a similar-looking issue in another project, and it seemed to be related to json-schema-ref-parser: https://github.com/cdimascio/express-openapi-validator/issues/183#issuecomment-566243768

**Comment by suhailopensource** [comment]
@Xiphe i have been looking into the codebase for a while now . i think i can fix this . can u assign it to me ?
